#!/usr/bin/env python3
X=print
R=range
B=False
M=ValueError
H=bytearray
E=len
import struct as W
from PIL import Image
import sys as A
def D(input_path,output_path,use_default_vga=B,small=B,mono=B,tiny=B,rle=B):
	Z=output_path;Y=input_path;Q='No palette found';O=None;J=Image.open(Y)
	if J.mode!='P'and not(mono or tiny):raise M('Image must be paletted (indexed) for paletted NSBMP types')
	S,a=J.size;B=list(J.getdata());P=b'Bm'
	if mono:F=b'M'
	elif tiny:F=b'T'
	elif small:F=b'R'
	elif rle:F=b'L'
	elif use_default_vga:F=b'V'
	else:F=b'C'
	P+=F;P+=W.pack('<H',S);P+=W.pack('<H',a)
	with open(Z,'wb')as G:
		G.write(P)
		if F==b'M':
			A=J.getpalette()
			if A is O:A=[0,0,0,255,255,255]
			D=6;A=A[:D]+[0]*(D-E(A));A=[A//4 for A in A];G.write(H(A));I=H()
			for b in R(a):
				e=B[b*S:(b+1)*S];K,N=0,0
				for f in e:
					g=f&1;K=K<<1|g;N+=1
					if N==8:I.append(K);K=0;N=0
				if N>0:K<<=8-N;I.append(K)
			G.write(I)
		elif F==b'T':
			A=J.getpalette()
			if A is O:raise M(Q)
			D=12;A=A[:D]+[0]*(D-E(A));A=[A//4 for A in A];G.write(H(A));I=H()
			for C in R(0,E(B),4):T=B[C]&3;U=B[C+1]&3 if C+1<E(B)else 0;h=B[C+2]&3 if C+2<E(B)else 0;i=B[C+3]&3 if C+3<E(B)else 0;I.append(T<<6|U<<4|h<<2|i)
			G.write(I)
		elif F==b'R':
			A=J.getpalette()
			if A is O:raise M(Q)
			D=48;A=A[:D]+[0]*(D-E(A));A=[A//4 for A in A];G.write(H(A));I=H()
			for C in R(0,E(B),2):T=B[C]&15;U=B[C+1]&15 if C+1<E(B)else 0;I.append(T<<4|U)
			G.write(I)
		elif F==b'C':
			A=J.getpalette()
			if A is O:raise M(Q)
			D=768;A=A[:D]+[0]*(D-E(A));A=[A//4 for A in A];G.write(H(A));G.write(H(B))
		elif F==b'V':G.write(H(B))
		elif F==b'L':
			A=J.getpalette()
			if A is O:raise M(Q)
			D=768;A=A[:D]+[0]*(D-E(A));A=[A//4 for A in A];G.write(H(A));V=H();C=0;c=E(B)
			while C<c:
				d=B[C];L=1
				while C+L<c and B[C+L]==d and L<255:L+=1
				V.append(L);V.append(d);C+=L
			G.write(V)
	X(f"[OK] Converted {Y} -> {Z} (NSBMP 2.0, subtype {F.decode()})")
if __name__=='__main__':
	if E(A.argv)<3:X('Usage: python bmp2nsbmp.py input.bmp output.raw [-v] [-r] [-m] [-t] [-l]');A.exit(1)
	F='-v'in A.argv;G='-r'in A.argv;I='-m'in A.argv;J='-t'in A.argv;K='-l'in A.argv;C=[A for A in A.argv[1:]if A not in['-v','-r','-m','-t','-l']];L=C[0];N=C[1];D(L,N,F,G,I,J,K)